name: Node.js CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Type coverage check
        run: npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
